extraction:
  cpp:
    after_prepare: 
      - python report.py 98
  cobol:
    after_prepare: 
      - python report.py 98
  csharp:
    after_prepare: 
      - python report.py 98
  java:
    after_prepare: 
      - python report.py 98
  javascript:
    after_prepare: 
      - python report.py 98
  python:
    after_prepare: 
      - python report.py 98
